version: "3.7"

services:
  database:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: logindb
      MYSQL_ROOT_PASSWORD: P12345p
      MYSQL_USER: admin
      MYSQL_PASSWORD: ProjectGroup_1
    networks: 
      - cloudnet
  my-app:
    image: projectgroup/login:latest
    restart: always
    depends_on:
      - database
    ports:
      - "80:80"
    networks:
      - cloudnet
networks:
  cloudnet:
    driver: bridge
