apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    name: mysql-service
spec:
  selector:
    name: mysql-pod
  clusterIP: None
  ports:
    - name: db
      port: 3306
      targetPort: 3306

